import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Panel } from "@/components/oraculum/Panel";
import { StatusBadge } from "@/components/oraculum/StatusIndicator";
import { useSession } from "@/components/oraculum/session";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { connectionLabel, connectionTone, logLevelLabel, logLevelTone, monitoringLabel } from "@/lib/status";
import { diagnosticService, machineService } from "@/services/oraculum";
import type { LogLevel } from "@/mock/types";

export const Route = createFileRoute("/diagnostico")({
  head: () => ({ meta: [{ title: "Diagnóstico — Oraculum" }, { name: "description", content: "Diagnóstico técnico simulado da comunicação e aquisição do Oraculum." }, { property: "og:title", content: "Diagnóstico — Oraculum" }, { property: "og:description", content: "Diagnóstico técnico simulado da comunicação e aquisição do Oraculum." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: DiagnosticsPage,
});

function DiagnosticsPage() {
  const session = useSession(); const snapshot = diagnosticService.snapshot(); const machine = machineService.list().find((item) => item.id === session.machineId); const [level, setLevel] = useState("all"); const events = diagnosticService.events().filter((event) => level === "all" || event.level === level);
  const cards = [["Comunicação com o adaptador", connectionLabel(session.connection), connectionTone(session.connection)],["Registros do formulário", session.connection === "connected" ? "41 / 41" : "0 / 41", session.connection === "connected" ? "ok" : "idle"],["Amostras recebidas", snapshot.samplesReceived.toLocaleString("pt-BR"), "info"],["Amostras perdidas", snapshot.samplesLost.toLocaleString("pt-BR"), snapshot.samplesLost ? "warn" : "ok"]] as const;
  return <div className="space-y-4"><header><p className="tech-label">Sistema / Saúde técnica</p><h1 className="font-display text-2xl font-semibold uppercase">Diagnóstico</h1><p className="text-sm text-muted-foreground">Estado simulado do adaptador e da aquisição.</p></header>
    <section className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value,tone]) => <div key={label} className="panel-surface p-3"><span className="tech-label">{label}</span><div className="mt-3 flex items-center justify-between"><strong className="readout text-xl">{value}</strong><StatusBadge tone={tone} label={tone === "ok" ? "Normal" : tone === "warn" ? "Atenção" : tone === "fault" ? "Falha" : "Info"} /></div></div>)}</section>
    <div className="grid gap-3 xl:grid-cols-3"><Panel title="Comunicação"><Diag label="Máquina selecionada" value={machine?.name ?? "Nenhuma"} /><Diag label="Protocolo" value={machine?.protocol ?? "--"} /><Diag label="Estado do adaptador" value={connectionLabel(session.connection)} /><Diag label="Latência" value={session.connection === "connected" ? `${snapshot.latencyMs} ms` : "--"} /><Diag label="Última leitura" value={snapshot.lastReadAt} /><Diag label="Última mensagem de erro" value={session.connection === "disconnected" ? "Tempo limite de leitura simulado" : "Nenhuma"} /></Panel><Panel title="Aquisição"><Diag label="Estado" value={monitoringLabel(session.monitoring)} /><Diag label="Taxa" value={`${snapshot.sampleRateHz} Hz`} /><Diag label="Processo de leitura" value={session.monitoring === "running" ? "EM EXECUÇÃO" : "OCIOSO"} /><Diag label="Geração de resultados" value={session.scenario === "partial-save" ? "PARCIAL" : "DISPONÍVEL"} /></Panel><Panel title="Sistema"><Diag label="Versão" value={snapshot.version} /><Diag label="Adaptador" value="Simulado · sem conexão real" /><Diag label="Interface" value="Oraculum V2" /><Diag label="Última atualização" value={snapshot.updatedAt} /></Panel></div>
    <Panel title="Eventos" subtitle={`${events.length} registros`} actions={<Select value={level} onValueChange={setLevel}><SelectTrigger className="w-40"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Todos</SelectItem>{(["INFO","WARNING","ERROR"] as LogLevel[]).map((item) => <SelectItem key={item} value={item}>{logLevelLabel(item)}</SelectItem>)}</SelectContent></Select>} bodyClassName="max-h-[360px] overflow-y-auto p-0"><div className="divide-y divide-border">{events.map((event) => <div key={event.id} className="grid gap-2 px-3 py-2 text-xs sm:grid-cols-[170px_110px_110px_1fr]"><span className="readout text-muted-foreground">{new Date(event.timestamp).toLocaleString("pt-BR")}</span><StatusBadge tone={logLevelTone(event.level)} label={logLevelLabel(event.level)} /><span className="font-mono text-muted-foreground">{event.source}</span><span>{event.message}</span></div>)}</div></Panel>
  </div>;
}
function Diag({ label, value }: { label: string; value: string }) { return <div className="flex items-start justify-between gap-4 border-b border-border py-2 last:border-0"><span className="text-xs text-muted-foreground">{label}</span><strong className="readout text-right text-xs">{value}</strong></div>; }